### ISSUE TITLE
Project won't run

### ISSUE THREAD

**Issue by MBre111** [kulltc/chatgpt-sql#3]
When attempting to run the terminal after extracting ZIP, I get the following error:

File "c:\Users\mbre\GitHub\chatgpt-sql\chatgpt.py", line 2, in <module>
    import openai

**Comment by kulltc** [comment]
My bad I didn't include the requirements.txt. It should work now after you redownload, then run `pip install -r requirements.txt`

Alternatively, you can run the following commands locally:

```
pip freeze > requirements.txt
pip install -r requirements.txt
```
