### ISSUE TITLE
new to python

### ISSUE THREAD

**Issue by MatrixTools** [kulltc/chatgpt-sql#8]
sorry if this is not the proper channel.  but i'm brand new to python.

I dont see a main.py file.. :(  how hard is it to build that file (i literally know 0 about python just wanted to try this project out)  :( sorry!

i have tried everything i can think of...
i feel like i might be missing like 1 step to be able to learn how to build this?

sorry!

**Comment by kulltc** [comment]
No problem. Use terminal.py instead of main.py
